import React from "react";
import Head from "next/head";

import CartTemplate from "@/components/templates/Cart";

const Cart = () => {
  return (
    <>
      <Head>
        <title>Teste Front React WeFit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CartTemplate />
      </main>
    </>
  );
};

export default Cart;
