import Head from "next/head";

import HomeTemplate from "@/components/templates/Home";

const Home = () => {
  return (
    <>
      <Head>
        <title>Teste Front React WeFit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeTemplate />
      </main>
    </>
  );
};

export default Home;
